import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../lib/theme/globals.css";

const inter = Inter({ subsets: ["latin"] });

import { css } from "styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* SiteHeader */}
        <h1
          className={css({ color: "red", fontSize: "2xl", fontWeight: "bold" })}
        >
          Panda ready...
        </h1>
        {children}
        {/* SiteFooter */}
      </body>
    </html>
  );
}
